# Generated by Django 5.1.1 on 2024-09-24 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
        migrations.AddField(
            model_name='worker',
            name='profile_pic',
            field=models.ImageField(blank=True, upload_to='profiles/'),
        ),
    ]
