# Generated by Django 5.1.1 on 2024-11-18 06:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_worker_appointed'),
    ]

    operations = [
        migrations.AddField(
            model_name='worker',
            name='appointment_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
