# Generated by Django 5.1.1 on 2024-11-20 03:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0005_customer_latitude_customer_longitude_worker_latitude_and_more'),
        ('jobs', '0010_remove_appointment_date_appointment_appointment_date_and_more'),
    ]

    operations = [
    ]
