# Generated by Django 5.1.1 on 2024-11-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_merge_20241120_0902'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointment',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='appointment',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
