# Generated by Django 5.1.1 on 2024-12-15 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_workerrating'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workerrating',
            name='appointment',
        ),
        migrations.AddField(
            model_name='workerrating',
            name='appointment',
            field=models.ManyToManyField(related_name='ratings', to='jobs.appointment'),
        ),
    ]
