# Generated by Django 5.1.1 on 2025-01-28 08:46

import phonenumber_field.modelfields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_workerrating_worker'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP', unique=True),
        ),
        migrations.AlterField(
            model_name='worker',
            name='phone_number',
            field=phonenumber_field.modelfields.PhoneNumberField(max_length=128, region='NP', unique=True),
        ),
    ]
